// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SevenFactorData } from "./SevenFactorData";

/**
 * 7Factor 응답용 타입
 */
export type SevenFactorResponse = { ticker: string, name: string, market: string, 
/**
 * 7개 정규화 팩터 (0-100)
 */
factors: SevenFactorData, 
/**
 * 종합 점수 (0-100) - JSON에서 숫자로 직렬화
 */
composite_score: number, 
/**
 * 기존 GlobalScore 정보 - JSON에서 숫자로 직렬화
 */
global_score: number | null, grade?: string, 
/**
 * 계산 시각
 */
calculated_at: string, };
