// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldType } from "./FieldType";

/**
 * 필드 스키마.
 */
export type FieldSchema = { 
/**
 * 필드 이름 (snake_case)
 */
name: string, 
/**
 * 필드 타입 (프론트엔드와 동일한 키 이름 사용)
 */
field_type: FieldType, 
/**
 * 표시 라벨 (한글)
 */
label: string, 
/**
 * 설명 (옵션)
 */
description?: string, 
/**
 * 기본값 (JSON 값)
 */
default?: unknown, 
/**
 * 최소값 (number/integer 타입)
 */
min?: number, 
/**
 * 최대값 (number/integer 타입)
 */
max?: number, 
/**
 * 선택 옵션 (select/multi_select 타입)
 */
options: Array<string>, 
/**
 * 조건부 표시 (예: "enabled == true")
 */
condition?: string, 
/**
 * 필수 여부
 */
required: boolean, 
/**
 * 숨김 여부 (UI에서 표시하지 않음)
 */
hidden: boolean, 
/**
 * 표시 순서 (낮을수록 먼저 표시)
 */
order?: number, 
/**
 * 섹션 ID (같은 섹션의 필드들을 UI에서 그룹화)
 *
 * 예: "indicator" → "기술적 지표" 섹션으로 그룹화
 * 예: "filter" → "필터 조건" 섹션으로 그룹화
 * 예: "asset" → "자산 선택" 섹션으로 그룹화
 */
section?: string, };
