// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 개별 거래 결과 (매수 또는 매도 단일 거래)
 * BacktestRunResponse.all_trades에 사용
 */
export type TradeResultItem = { 
/**
 * 심볼
 */
symbol: string, 
/**
 * 방향 (buy/sell)
 */
side: string, 
/**
 * 신호 유형 (entry, exit, add_to_position 등)
 */
signal_type: string, 
/**
 * 체결 수량
 */
quantity: string, 
/**
 * 체결 가격
 */
price: string, 
/**
 * 수수료
 */
commission: string, 
/**
 * 슬리피지 금액
 */
slippage: string, 
/**
 * 체결 시간 (ISO 8601)
 */
timestamp: string, 
/**
 * 실현 손익 (청산 거래인 경우)
 */
realized_pnl?: string, 
/**
 * 분할 매수/매도 여부
 */
is_partial: boolean, 
/**
 * 메타데이터
 */
metadata: { [key in string]: string }, };
