// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 수행할 액션의 종류를 나타내는 신호 유형.
 */
export type SignalType = "entry" | "exit" | "alert" | "add_to_position" | "reduce_position" | "scale";
